name: Decommission Plan

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  destroy-plan:
    uses: FA9-lab/platform-workflows/.github/workflows/terraform-destroy-plan.yml@feature/deployment-repo-plan
    with:
      deployment-name: "orders-prod-eastus-iyj69e-CHG123456"
      working-directory: "."
    secrets: inherit
