name: Infrastructure Plan

on:
  pull_request:
    branches:
      - main
permissions:
  id-token: write
  contents: read
  
jobs:
  plan:
    uses: FA9-lab/platform-workflows/.github/workflows/terraform-plan.yml@feature/deployment-repo-plan
    with:
      deployment-name: "orders-prod-eastus-iyj69e-CHG123456"
      working-directory: "."
    secrets: inherit
